# Generated by Django 3.0.6 on 2020-06-07 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20200607_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='potfolio_site',
            new_name='portfolio_site',
        ),
    ]
